version: '3.8'

services:
  news-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_GUARDIAN_API_KEY=${VITE_GUARDIAN_API_KEY}
        - VITE_GUARDIAN_API_URL=${VITE_GUARDIAN_API_URL}
        - VITE_NEWS_API_KEY=${VITE_NEWS_API_KEY}
        - VITE_NEWS_API_URL=${VITE_NEWS_API_URL}
        - VITE_NY_TIMES_API_KEY=${VITE_NY_TIMES_API_KEY}
        - VITE_NY_TIMES_API_URL=${VITE_NY_TIMES_API_URL}
    ports:
      - "3000:80"
    environment:
      - VITE_GUARDIAN_API_KEY=${VITE_GUARDIAN_API_KEY}
      - VITE_GUARDIAN_API_URL=${VITE_GUARDIAN_API_URL}
      - VITE_NEWS_API_KEY=${VITE_NEWS_API_KEY}
      - VITE_NEWS_API_URL=${VITE_NEWS_API_URL}
      - VITE_NY_TIMES_API_KEY=${VITE_NY_TIMES_API_KEY}
      - VITE_NY_TIMES_API_URL=${VITE_NY_TIMES_API_URL}
      - VITE_CURRENT_DATETIME=$(date '+%Y-%m-%d %H:%M:%S')
      - VITE_CURRENT_USER=alirezamirehe
    restart: unless-stopped